# Generated by Django 4.1.7 on 2023-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
