# Generated by Django 4.1.7 on 2023-03-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_post_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.recipe'),
        ),
    ]
