# Generated by Django 4.1.7 on 2023-03-27 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_post_photo_url_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='white_balance_shift',
            new_name='white_balance_shift_blue',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='color_saturation',
        ),
        migrations.AddField(
            model_name='recipe',
            name='white_balance_shift_red',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-9), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='exposure_compensation',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='iso',
            field=models.CharField(choices=[('Auto', 'Auto'), ('200', '200'), ('400', '400'), ('800', '800'), ('1600', '1600'), ('3200', '3200'), ('6400', '6400'), ('12800', '12800')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='white_balance',
            field=models.CharField(max_length=50),
        ),
    ]
